[0m13:45:06.001610 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029F6CE57490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029F6C6F4410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029F6C982D50>]}


============================== 13:45:06.019946 | 64a5c773-5252-4bb3-82c5-9aa9b9ceb274 ==============================
[0m13:45:06.019946 [info ] [MainThread]: Running with dbt=1.7.0
[0m13:45:06.023940 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:45:06.026940 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\user\Documents\Northwind 2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:45:06.033938 [debug] [MainThread]: Command `dbt run` failed at 13:45:06.032939 after 0.19 seconds
[0m13:45:06.034934 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029F6C983990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029F6C9565D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029F6C765150>]}
[0m13:45:06.037934 [debug] [MainThread]: Flushing usage events
[0m11:56:34.677437 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC22225450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC22225E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC2230F150>]}


============================== 11:56:34.698280 | 27c51d6b-c469-468c-9245-f2110054ac8e ==============================
[0m11:56:34.698280 [info ] [MainThread]: Running with dbt=1.7.0
[0m11:56:34.702288 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init Northwind2', 'send_anonymous_usage_stats': 'True'}
[0m11:56:34.712363 [debug] [MainThread]: Starter project path: C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m11:56:34.777514 [info ] [MainThread]: 
Your new dbt project "Northwind2" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:56:34.777514 [info ] [MainThread]: Setting up your profile.
[0m11:56:39.477983 [debug] [MainThread]: Command `dbt init` succeeded at 11:56:39.477983 after 5.00 seconds
[0m11:56:39.480930 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC22244110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC1B413710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC223148D0>]}
[0m11:56:39.483268 [debug] [MainThread]: Flushing usage events
[0m13:16:09.839643 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246D2200890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246D1E13E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246D1A6B950>]}


============================== 13:16:09.860171 | e3de1456-9e0e-45d8-9bbd-7232f9d52bd4 ==============================
[0m13:16:09.860171 [info ] [MainThread]: Running with dbt=1.7.0
[0m13:16:09.885438 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:16:09.889439 [info ] [MainThread]: dbt version: 1.7.0
[0m13:16:09.977739 [info ] [MainThread]: python version: 3.11.9
[0m13:16:10.038983 [info ] [MainThread]: python path: C:\Users\user\AppData\Local\Programs\Python\Python311\python.exe
[0m13:16:10.114439 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m13:16:10.886793 [info ] [MainThread]: Using profiles dir at C:\Users\user\.dbt
[0m13:16:10.939281 [info ] [MainThread]: Using profiles.yml file at C:\Users\user\.dbt\profiles.yml
[0m13:16:11.013140 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\user\Documents\Northwind 2\dbt_project.yml
[0m13:16:11.066137 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m13:16:11.141338 [debug] [MainThread]: Command `dbt debug` failed at 13:16:11.140338 after 1.70 seconds
[0m13:16:11.143335 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246D2240950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246D1A4E510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246D1D47F50>]}
[0m13:16:11.146334 [debug] [MainThread]: Flushing usage events
[0m16:16:08.327150 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000206E2C0B950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000206DF804C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000206E246BE50>]}


============================== 16:16:08.341828 | 34e91e97-dfe2-49b0-8d57-a483f445e37d ==============================
[0m16:16:08.341828 [info ] [MainThread]: Running with dbt=1.7.0
[0m16:16:08.361971 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:16:08.366977 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\user\Documents\Northwind 2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:16:08.377041 [debug] [MainThread]: Command `dbt run` failed at 16:16:08.377041 after 0.42 seconds
[0m16:16:08.380084 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000206E250FED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000206E250D150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000206E2735250>]}
[0m16:16:08.382115 [debug] [MainThread]: Flushing usage events
[0m14:21:24.241884 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211C65A12D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211C5DF3450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211C6065F10>]}


============================== 14:21:24.266214 | 6f39f75d-4db4-4212-9b9f-7617d170d69a ==============================
[0m14:21:24.266214 [info ] [MainThread]: Running with dbt=1.7.0
[0m14:21:24.274494 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:21:24.274494 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\user\Documents\Northwind 2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:21:24.282494 [debug] [MainThread]: Command `dbt run` failed at 14:21:24.282494 after 0.39 seconds
[0m14:21:24.282494 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211C5DD7490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211C6569410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211BF206950>]}
[0m14:21:24.290871 [debug] [MainThread]: Flushing usage events
[0m19:00:06.598309 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DCF5CF3A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DCF59D41D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DCF5ADF5D0>]}


============================== 19:00:06.613937 | 5fceee01-afc6-41bf-b359-bbaeb14f4f2e ==============================
[0m19:00:06.613937 [info ] [MainThread]: Running with dbt=1.7.0
[0m19:00:06.613937 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:00:06.629556 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\user\Documents\Northwind 2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:00:06.635541 [debug] [MainThread]: Command `dbt run` failed at 19:00:06.635541 after 0.17 seconds
[0m19:00:06.635541 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DCF5CF3A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DCF5D65150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DCF5F80390>]}
[0m19:00:06.642009 [debug] [MainThread]: Flushing usage events
[0m14:32:51.574998 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016F41054E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016F41461090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016F3D8A0550>]}


============================== 14:32:51.605362 | c771f89f-2e40-42c3-baf9-04050751ad0d ==============================
[0m14:32:51.605362 [info ] [MainThread]: Running with dbt=1.7.0
[0m14:32:51.610359 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:32:51.612549 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\user\Documents\Northwind 2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:32:51.620544 [debug] [MainThread]: Command `dbt run` failed at 14:32:51.620544 after 0.27 seconds
[0m14:32:51.623542 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016F40D34110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016F40F53310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016F40EA19D0>]}
[0m14:32:51.626541 [debug] [MainThread]: Flushing usage events
